### ISSUE TITLE
提供未新增專案, 即可執行 python 程式的功能

### ISSUE THREAD

**Issue by mdecourse** [KmolYuan/kmol-editor#1]
目前啟動程式後, 若未新增專案時, 在編輯區輸入 Python 程式, 按下執行, 即因存檔物件無 text() 而當機, 應該允許在開啟後, 即可在編輯區輸入簡單 Python 程式後, 即可執行.

**Comment by KmolYuan** [comment]
已修正：https://github.com/KmolYuan/kmol-editor/commit/80769583c6c44dd9f0aaa13cb8a41504263dd844
