### ISSUE TITLE
新增未存檔前, 可執行 Flask 程式

### ISSUE THREAD

**Issue by mdecourse** [KmolYuan/kmol-editor#2]
例如:

    # 導入 Flask 類別
    from flask import Flask
    '''
    If you are using a single module (as in this
    example), you should use __name__ because depending on if it’s started as application
    or imported as module the name will be different ('__main__' versus
    the actual import name). This is needed so that Flask knows where to look for
    templates, static files, and so on. For more information have a look at the Flask
    documentation.
    '''
    # 利用 Flask 類別建立 app 案例
    app = Flask(__name__)
     
    '''
    The route decorator is used to register a view function for a given URL rule.
    This does the same thing as add_url_rule() but is intended for decorator.
    '''
    # 利用 decorator 設定 URL 連結
    @app.route('/')
    def hello_world():
        # 傳回字串
        return 'Hello, World!'
     
    # app 在本機埠號 5000 執行, 且開啟 debug 模式
    app.run(host='127.0.0.1', port=5000, debug=True)

**Comment by KmolYuan** [comment]
Flask 程式貌似只能在主執行緒執行，不然會回傳錯誤：`ValueError: signal only works in main thread`

搭配 gevent 模組的 Python2 PyQt4 範例：<https://gist.github.com/andrewbunday/1358794>

將其改成 Python3 PyQt5：

```python
import sys
import time

from flask import Flask
from PyQt5 import QtCore, QtGui, QtWidgets, QtWebEngineWidgets

import gevent
import gevent.pywsgi


class WebView(QtWebEngineWidgets.QWebEngineView):
    def __init__(self):
        super(WebView, self).__init__()
        self.load(QtCore.QUrl("http://localhost:5000/"))

    def mousePressEvent(self, event):
        self.close()

    def closeEvent(self, event):
        self.deleteLater()
        app.quit()
        print("closing gui")
        g.kill(gevent.GreenletExit, block=False)
        f.kill(gevent.GreenletExit, block=False)
        print("are gui and webserver alive? ", g.dead, f.dead)


class PyQtGreenlet(gevent.Greenlet):
    def __init__(self, app):
        gevent.Greenlet.__init__(self)
        self.app = app

    def _run(self):
        while True:
            self.app.processEvents()
            while self.app.hasPendingEvents():
                self.app.processEvents()
                gevent.sleep(0.01)
        gevent.sleep(0.1)


if __name__ == "__main__":
    fapp = Flask(__name__)
    fapp.debug=True

    @fapp.route("/")
    def hello():
        print(time.time())
        return '<a href="http://localhost:5000/bye" > quit() </a></br><a href="http://localhost:5000/" > reload </a></br>count={0}'.format(time.time())

    @fapp.route("/bye", methods=['GET'])
    def goodbye():
        print("killing webserver")
        f.kill(block=False)
        print("is webserver alive? ", f.dead)
        window.close()
        return 'goodbye'

    http_server = gevent.pywsgi.WSGIServer(('', 5000), fapp)
    f = gevent.spawn(http_server.serve_forever)

    app = QtWidgets.QApplication(sys.argv)  
    window = WebView()
    window.show()
    g = PyQtGreenlet.spawn(app)
    gevent.joinall([f, g])
```

不過此腳本的物件引用有些紊亂，Kmol Editor 或許可以將其包裝成簡單易懂的版本。

**Comment by mdecourse** [comment]
沒有關係, 此類程式或許就讓它在 SciTE 環境中執行即可.
